
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "user@gmail.com",
    "password": "password"
}
###
GET http://127.0.0.1:8000/api/user
Authorization: Bearer 3|liXupJGsUVQuZPcNOhcd7gATZw9YoP2hRvz0nn3c2444213d
### Crear una reserva
POST http://127.0.0.1:8000/api/reservas
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|liXupJGsUVQuZPcNOhcd7gATZw9YoP2hRvz0nn3c2444213d

{
    "usuario_id": 1,
    "actividad_id": 1,
    "cantidad_personas": 2,
    "notas": "Reserva de prueba"
}

### Listar reservas
POST  http://127.0.0.1:8000/api/reservas
Accept: application/json
Authorization: Bearer 3|liXupJGsUVQuZPcNOhcd7gATZw9YoP2hRvz0nn3c2444213d
